src/QueueableAction.php, tests/QueueableActionTest.php
If you are using prioritised queues you might want to allow for editing the queue name directly using the `onQueue` method.
This is a breaking change, so that is why I flagged it for v2.0.
=> [v2.0] Change queue name via onQueue

src/ActionJob.php, tests/ActionJobTest.php, tests/QueueableActionTest.php
I came a cross a situation, where I needed to dynamically chain other instances of `ActionJob` to the one being queued.
That can be accomplished like this:
```php
$this->actionOne->onQueue()
->execute($arg)
->chain([
new ActionJob(app(ActionTwo::class), [$argOne, $argTwo]),
new ActionJob(app(ActionThree::class), [$argOne, $argTwo]),
]);
```
After this PR it is no longer required to resolve the chained actions.
```php
$this->actionOne->onQueue()
->execute($arg)
->chain([
new ActionJob(ActionTwo::class, [$argOne, $argTwo]),
new ActionJob(ActionThree::class, [$argOne, $argTwo]),
]);
```
=> Pass the action class name directly to the ActionJob

src/ActionJob.php
As described in [this section of the Laravel documentation](https://laravel.com/docs/5.8/queues#max-job-attempts-and-timeout), you can override the "tries" and "timeout" properties of the queue inside your Laravel Job. This PR adds this ability to the ActionJob.
=> Add 'tries' and 'timeout' as queueable properties.

README.md, composer.json, src/ActionMakeCommand.php, src/QueueableActionServiceProvider.php, src/stubs/action-queued.stub, src/stubs/action.stub, tests/ActionMakeCommandTest.php, tests/TestCase.php, tests/stubs/test-action-queued.stub, tests/stubs/test-action.stub
For myself, and hopefully many others, this will be the missing link to making the jump from leveraging Jobs in a similar fashion now to Actions without any hindrance of workflows.
I erred on the side of conformity, following the command signature for generating jobs in Laravel which is asynchronous by default, synchronous with the `--sync` trigger. If it would be open for discussion, given the nature of Actions, it might make more sense to flip that and make generating actions synchronous by default and queueable with a `--queue` switch, or similar.
It took a minute to realize a test scenario which was both practical and yielded worthwhile results, but if there is a better way I would be very interested to know what that might be.
=> Implement make:action artisan command

.gitignore, src/ActionJob.php, tests/QueueableActionTest.php, tests/TestClasses/ActionWithFailedMethod.php, tests/TestClasses/FailingAction.php
Fixes #28 
Please review.
This can, hypothetically, be a breaking change: If someone had a `failed()` method, it would be executed on failures now. I'm not sure what's your approach with regards to semver, but I personally don't think this is an issue. Seems like an extremely rare case for this to be an issue.
=> failed() method support

src/ActionJob.php
Changed the Failed method's `$exception` type declaration from `Exception` to `Throwable`.
All tests pass.
=> Update Failed method to accept Throwable

README.md, src/Testing/QueueableActionFake.php, tests/Testing/QueueableActionTest.php
**Added**
- `assertPushedWithChain(string $actionClass, array $expextedActionChain = [])`
- `assertPushedWithoutChain(string $actionClass)`
Previously if you want to check for chained actions you would have to use Laravel's `assertPushed()` and do the matching with unserializing the `chain` yourself. Now you can assert the chains with:
```
Queue::fake();
(new SimpleAction)
->onQueue()
->execute()
->chain([
new ActionJob(ChainedAction::class),
new ActionJob(AnotherChainedAction::class),
]);
QueueableActionFake::assertPushedWithChain(SimpleAction::class, [ChainedAction::class, AnotherChainedAction::class]);
```
=> Add new QueueFake methods

README.md, src/ActionJob.php, src/QueueableAction.php, tests/QueueableActionTest.php, tests/TestClasses/BackoffAction.php, tests/TestClasses/BackoffPropertyAction.php
This pull request adds support for the [backoff method/property](https://laravel.com/docs/8.x/upgrade#queue-retry-after-method) introduced in Laravel 8.x.
=> Support for backoff method/property

src/ActionJob.php, tests/QueueableActionTest.php
I added a `Batchable` trait to the `ActionJob` in order batch actions.
It's not IDE-friendly, the IDE won't show you which parameters the action needs, and it's not a structured solution for batchable actions.
It's kinda a first step of the solution, I created an issue and I would be happy if you guys could comment there and discuss the ideal design. https://github.com/spatie/laravel-queueable-action/issues/40
Thanks!
=> Add `Batchable` trait to `ActionJob`

src/ActionJob.php, tests/QueueableActionTest.php, tests/TestClasses/CountRunsMiddleware.php
Laravel merges results from the middleware property and method, which results in applying middleware twice to the ActionJob.
This PR fixes that.
=> Fix for running middleware twice

src/Testing/QueueableActionFake.php, tests/TestClasses/QueueableActionFakeTestClass.php, tests/Testing/QueueableActionTest.php
The ability to use a custom `ActionJob` class was introduced in https://github.com/spatie/laravel-queueable-action/pull/46. It, however, did not update the QueueableActionFake class to also allow for it. This PR is to fix that.
I went with a possibly non-standard approach with the tests in that I created a test class to expose the protected methods on `QueueableActionFake`. I went this route so I could just add two additional tests to `QueueableActionTest` instead of duplicating most of the existing tests. I'd be glad to do that if you prefer.
=> Fixes QueueableActionFake to accommodate a custom action job class

src/QueueableAction.php
Hello,
Queueable actions may [define tags](https://github.com/spatie/laravel-queueable-action#custom-tags) as a handy way to organize actions on Horizon.
This PR adds the action class name as a default tag.
=> Default Action Tags

src/QueueableAction.php
Sorry, since I did the changes directly on GitHub UI I did not see that `tags` was already declared.
This fixes the issue introduced on v2.14.4
=> Remove duplicated tags function

src/ActionJob.php
This resolves the issue identified in https://github.com/spatie/laravel-queueable-action/issues/76
In our QueueableAction class we could have:
`public int $timeout = 240`
Currently when using ActionJob we get:
`PHP Warning:  Attempt to read property "timeout" on string in /Users/me/dev/example-laravel/vendor/spatie/laravel-queueable-action/src/ActionJob.php on line 151
`
This PR fix will now return _240_ whereas it previously returned the warning.
The $action variable is a string of the action ClassName, so we cannot access the $queueableProperty unless we first new up the class. Using the app() helper for this.
=> Access model properties in ActionJob

src/ActionJob.php
My apologies for missing this in https://github.com/spatie/laravel-queueable-action/pull/81
The previous PR will fix for ActionJob but break for QueuableActions called directly as they are passing the $action object as a parameter and not the class name. 
There is already a check in the constructor to determine if class name or class object is passed - so we can use that to resolve this:
https://github.com/spatie/laravel-queueable-action/blob/01da21e5044dd245669cd75922e211264bfee063/src/ActionJob.php#L40
=> Pass the Actions ClassName when Action called directly

src/ActionJob.php, tests/ActionMakeCommandTest.php
This [PR](https://github.com/laravel/framework/pull/44847) removed the __sleep and __wakeup methods. As this package also requires PHP 8.0 we can safely delete these methods too. See [reference](https://www.php.net/manual/en/language.oop5.magic.php#object.serialize)
Furthermore I fixed the test as the output slightly changed.
=> Remove __sleep & __wakeup from ActionJob

src/ActionJob.php
Allows to use "retryUntil" instead of "tries" which is pretty much a must when using a rate-limiting or WithoutOverlapping job middleware.
=> Added retryUntil to $queueableProperties

src/ActionJob.php, tests/QueueableActionTest.php, tests/TestClasses/RetryUntilAction.php
Hi,
thanks for this packages!
I added support for [Time Based Attempts](https://laravel.com/docs/11.x/queues#time-based-attempts) method
=> Support for retryUntil method

src/ActionJob.php, tests/QueueableActionTest.php, tests/TestClasses/ActionReturningAction.php, tests/TestClasses/ActionReturningJob.php
Hi,
I am submitting this pull request to enhance the job handling capabilities by explicitly passing the $job property into the job's action method. This addition allows developers to have more control over the job execution process, such as managing retries, deletions, and failures more effectively.
Moreover, this change improves compatibility with job monitoring packages, such as [Laravel-Queue-Monitor](https://github.com/romanzipp/Laravel-Queue-Monitor)
=> receives job property

.github/workflows/run-tests.yml, src/QueueableAction.php
This pull request introduces updates to the GitHub Actions workflow and the QueueableAction trait to ensure compatibility with PHP versions 8.3 and higher, **addressing the issue of deprecated dynamic properties**.
- Introduced a nullable `$job` property to the `QueueableAction` trait, preventing dynamic property warnings in PHP 8.2+.
- Added PHP 8.3 and 8.4 to the testing matrix, ensuring the package’s compatibility with the latest PHP versions.
#110
=> Fix: Add `$job` property to `QueueableAction` to address deprecated dynamic properties in PHP >= 8.2
